/*
 * Problem2.hpp
 *
 *  Created on: Jan 22, 2015
 *      Author: ryanluedders
 *
 *  Each new term in the Fibonacci sequence is generated by adding the
 *  previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *  By considering the terms in the Fibonacci sequence whose values do not
 *  exceed four million, find the sum of the even-valued terms.
 */

#ifndef PROBLEM2_PROBLEM2_HPP_
#define PROBLEM2_PROBLEM2_HPP_

namespace Problem {

	class Problem2 {
	private:
		static const int LIMIT = 4000000;

	public:
		static int findSumOfEvenFibonacciNumbersBelow(int below = LIMIT);
	};

}

#endif /* PROBLEM2_PROBLEM2_HPP_ */
